/*
 *  CWX_Defines.h
 *  CoreWarX
 *
 *  Created by Josh Freeman on 11/18/07.
 *  Copyright 2007 Twilight Edge Software. All rights reserved.
 *
 */

// Simulator
#define SIMULATOR_MEMORY_ARRAY_SIZE				8000
#define SIMULATOR_MAX_NUM_PROCESSES				64
#define SIMULATOR_MAX_ALLOWED_CYCLES			32000L

#define SIMULATOR_NUM_IMMEDIATE_MODE_REGISTERS			2
#define SIMULATOR_IMMEDIATE_MODE_REGISTER_A_ADDRESS		SIMULATOR_MEMORY_ARRAY_SIZE
#define SIMULATOR_IMMEDIATE_MODE_REGISTER_B_ADDRESS		SIMULATOR_MEMORY_ARRAY_SIZE+1

// Memory Array View
#define MEMORY_ARRAY_VIEW_ROW_WIDTH			125
#define MEMORY_ARRAY_VIEW_COL_HEIGHT		64
#define MEMORY_ARRAY_VIEW_CELL_SIZE			7

// Redcode Program
#define REDCODE_PROGRAM_MAX_NUM_INSTRUCTIONS	500

// Tournament Scoring
#define TOURNAMENT_POINTS_PER_WIN			3
#define TOURNAMENT_POINTS_PER_TIE			1
#define TOURNAMENT_POINTS_PER_LOSS			0

// Match Scoring
#define MATCH_POINTS_PER_WIN				3
#define MATCH_POINTS_PER_TIE				1
#define MATCH_POINTS_PER_LOSS				0

#define BATTLES_PER_MATCH					7
