#import "SpaceController.h"

@implementation SpaceController

- (void)awakeFromNib
{
	NSMutableArray * planets = [[NSMutableArray alloc] init];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Sun",@"The Sun is the star of our solar system. The Earth and other matter (including other planets, asteroids, meteoroids, comets and dust) orbit the Sun, which by itself accounts for more than 99% of the solar system's mass. Energy from the Sun—in the form of insolation from sunlight—supports almost all life on Earth via photosynthesis, and drives the Earth's climate and weather.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Mercury",@"Physically, Mercury is similar in appearance to the Moon as it is heavily cratered. It has no natural satellites and no substantial atmosphere. The planet has a large iron core which generates a magnetic field about 1% as strong as that of the Earth. Surface temperatures on Mercury range from about 90 to 700 K (-180 to 430°C) , with the subsolar point being the hottest and the bottoms of craters near the poles being the coldest.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Venus",@"Venus' surface has been mapped in detail only in the last 20 years. It shows evidence of extensive volcanism, and some of its volcanoes may still be active today. In contrast to the constant crustal movement seen on Earth, Venus is thought to undergo periodic episodes of plate tectonics, in which the crust is subducted rapidly within a few million years separated by stable periods of a few hundred million years.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Earth",@"Since it formed, the Earth has changed through geological and biological processes that have hidden traces of the original conditions. The outer surface is divided into several tectonic plates that gradually migrate across the surface over geologic time spans. The interior of the planet remains active, with a thick layer of convecting yet solid Earth mantle and an iron core that generates a magnetic field. Its atmospheric conditions have been significantly altered by the presence of life forms, which create an ecological balance that modifies the surface conditions. About 71% of the surface is covered in salt-water oceans, and the remainder consists of continents and islands.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Mars",@"Until the first flyby of Mars by Mariner 4 in 1965, it was hoped, both within and especially perhaps outside scientific circles, especially in the popular media and literary circles, that Mars had ample liquid water as was inferable from periodic variations in light and dark patches, particularly in the polar latitudes, and perhaps even irrigation channels of liquid water, as had been romanticized by several prominent SF authors, including the influential SF giants Burroughs (Barsoom series) and Robert A. Heinlein (from 1949-1963: Red Planet, Rolling Stones, Between Planets, Double Star, and finally, Podkayne of Mars, all prior to the mid-sixties. This was a myth inadvertently created by the press corps of the 1870—1880s based on a mistranslation of the Italian word 'Canali' (channel) used by astronomer Giovanni Schiaparelli English 'Canal', which became something of a fixation for the American astronomer Percival Lowell who wrote three books on the subject, fueling the myth.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Jupiter",@"Jupiter is 2.5 times more massive than all the other planets combined, so massive that its barycenter with the Sun actually lies above the Sun's surface (1.068 solar radii from the Sun's center). It is 318 times more massive than Earth, with a diameter 11 times that of Earth, and a volume 1300 times that of Earth. Quite naturally, Jupiter's gravitational influence has dominated the evolution of the solar system: most planets' orbits lie closer to Jupiter's orbital plane than the Sun's equatorial plane (Mercury is the only planet which is closer to the Sun's equator in orbital tilt), the majority of short-period comets belong to Jupiter's family (a result due to both Jupiter's mass and its relative speed), the Kirkwood gaps in the asteroid belt are mostly due to Jupiter, and Jupiter is even thought to have been possibly responsible for the Late Heavy Bombardment of the inner solar system's history. Some have described the solar system as consisting of the Sun, Jupiter, and assorted debris.[1] Some describe Jupiter as the solar system's vacuum cleaner, due to its immense gravity well.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Saturn",@"Saturn is an oblate spheroid, i.e. it is flattened at the poles and bulging at the equator; its equatorial and polar diameters vary by almost 10% (120,536 km vs. 108,728 km). This is the result of its rapid rotation and fluid state. The other gas planets are also oblate, but to a lesser degree. Saturn is the only one of the Solar System's planets that is less dense than water, with an average specific density of 0.69. This is a mean value; Saturn's upper atmosphere is less dense and its core is considerably more dense than water.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Uranus",@"Uranus is the first planet discovered in modern times. Sir William Herschel formally discovered the planet on March 13, 1781; the other planets (from Mercury out to Saturn) have been known since ancient times, and Uranus' discovery expanded the boundaries of the solar system for the first time in modern human history. It was also the first planet discovered using technology (a telescope) rather than the naked eye.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Neptune",@"Discovered on September 23, 1846, Neptune is notable for being the first planet discovered based on mathematical prediction rather than regular observations. Perturbations in the orbit of Uranus led astronomers to deduce Neptune's existence. It has been visited by only one spacecraft, Voyager 2, which flew by the planet on August 25, 1989. In 2003, there was a proposal to NASA's Vision Missions Studies to implement a Neptune Orbiter with Probes mission that does Cassini-level science without fission-based electric power or propulsion. The work is being done in conjunction with JPL and the California Institute of Technology.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	[planets addObject:[NSMutableDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Pluto",@"The history of how Pluto was discovered is intertwined with the discoveries of Neptune and Uranus. In the 1840s, using Newtonian mechanics, Urbain Le Verrier, and John Couch Adams had correctly predicted the position of the then-undiscovered planet Neptune after analysing perturbations in the orbit of Uranus. Theorizing the perturbations were caused by the gravitational pull of another planet, Johann Gottfried Galle discovered Neptune on September 23, 1846.",nil] forKeys:[NSArray arrayWithObjects:@"Name",@"Description",nil]]];
	
	[planetController setContent:planets];
	
	[mainView setNextPosition:[spaceSlider doubleValue]];
	[infoDrawer open];
}

- (IBAction)panThroughSpace:(id)sender
{
	//NSLog(@"position: %f", [sender doubleValue]);
	[mainView setNextPosition:[sender doubleValue]];
}

- (void)finishedScrollingAndLandedOn:(int)index
{
	[planetController setSelectionIndexes:[NSIndexSet indexSetWithIndex:index]];
}

@end
