//
//  ScreenSaverHack.h
//  Viva
//
//  Created by Daniel Jalkut on 3/30/07.
//  Copyright 2007 __MyCompanyName__. All rights reserved.
//

#import <ScreenSaver/ScreenSaver.h>

/*
 *     Generated by class-dump (version 2.1.5).
 *
 *     class-dump is Copyright (C) 1997, 1999, 2000, 2001 by Steve Nygard.
 */

@protocol ScreenSaverControl
- (void)screenSaverDidFadeInBackground:(char)fp8 psnHi:(unsigned int)fp12 psnLow:(unsigned int)fp16;
- (char)screenSaverIsRunningInBackground;
- (void)screenSaverDidFade;
- (double)screenSaverTimeRemaining;
- (void)restartForUser:fp8;
- (void)screenSaverStopNow;
- (void)screenSaverStartNow;
- (void)setScreenSaverCanRun:(char)fp8;
- (char)screenSaverCanRun;
- (char)screenSaverIsRunning;
@end

@interface ScreenSaverModules:NSObject
{
    NSMutableDictionary *_modules;
    NSMutableDictionary *_times;
    int _searchDomains;
    NSMutableArray *_sortedModuleNames;
    int _indexOfFirstAppleModule;
    int _indexOfLastAppleModule;
    int _indexOfChooseFolderItem;
    int _indexOfDotMacModule;
    int _indexOfPicturesFolderModule;
    int _indexOfUserSelectedFolderItem;
    int _indexOfFirstIPhotoAlbumModule;
    int _indexOfLastIPhotoAlbumModule;
    int _indexOfIPhotoLibraryAlbumModule;
    int _indexOfFirstApertureProject;
    int _indexOfLastApertureProject;
    int _indexOfApertureLibrary;
}

+ sharedInstance;
- init;
- (void)dealloc;
- (int)moduleSearchDomains;
- (void)setModuleSearchDomains:(int)fp8;
- _directoriesInSearchDomain;
- (void)findModulesWithOrder:fp8;
- (int)indexOfFirstAppleModule;
- (int)indexOfLastAppleModule;
- (int)indexOfChooseFolderItem;
- (int)indexOfDotMacModule;
- (int)indexOfPicturesFolderModule;
- (int)indexOfUserSelectedFolderItem;
- (int)indexOfFirstIPhotoAlbumModule;
- (int)indexOfLastIPhotoAlbumModule;
- (int)indexOfIPhotoLibraryAlbumModule;
- (int)indexOfFirstApertureProject;
- (int)indexOfLastApertureProject;
- (int)indexOfApertureLibrary;
- basicModuleName;
- slideShowModuleName;
- moduleNames;
- displayModuleNames;
- pathForModuleName:fp8;
- pathToLastUserSelectedFolder;
- (void)setUserSelectedFolderName:fp8;
- (Class)classForModuleWithName:fp8;
- (Class)classForModuleWithPath:fp8;
- loadModuleWithName:fp8;
- loadModuleWithName:fp8 frame:(struct _NSRect)fp12 isPreview:(char)fp28;
- loadModuleWithPath:fp8;
- loadModuleWithPath:fp8 frame:(struct _NSRect)fp12 isPreview:(char)fp28;
- (int)browser:fp8 numberOfRowsInColumn:(int)fp12;
- (void)browser:fp8 willDisplayCell:fp12 atRow:(int)fp16 column:(int)fp20;
- (char)browser:fp8 selectRow:(int)fp12 inColumn:(int)fp16;

@end

@interface ScreenSaverDefaultsManager:NSObject
{
    NSMutableDictionary *_cache;
}

+ defaultsManager;
- init;
- defaultsForKey:fp8;
- (void)setDefaults:fp8 forKey:fp12;
- (void)synchronize;
- (void)_appWillTerminate:fp8;

@end

@interface ScreenSaverUserInfo:NSObject
{
    unsigned int _eventHandle;
}

+ sharedInstance;
- init;
- (void)loginUserName:(id *)fp8 andID:(unsigned int *)fp12;
- (unsigned int)uidForUserName:fp8;
- (double)idleTime;

@end

@interface ScreenSaverWindow:NSWindow
{
    NSMutableArray *_trectTags;
}

- initWithContentRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24 backing:(int)fp28 defer:(char)fp32;
- (char)canBecomeKeyWindow;
- (char)canBecomeMainWindow;
- (void)startAnimating;
- (void)stopAnimating;
- (int)_setTrackingRect:(struct _NSRect)fp8 inside:(char)fp24 owner:fp28 userData:(void *)fp32 useTrackingNum:(int)fp36;
- (void)_discardTrackingRect:(int)fp8;
- (void)removeAllTrackingRects;
- (void)_cancelKey:fp8;

@end

@interface ScreenSaverController:NSObject <ScreenSaverControl>
{
    NSConnection *_connection;
    id _daemonProxy;
    void *_reserved;
}

+ controller;
+ monitor;
+ daemonConnectionName;
+ enginePath;
- (void)_connectionClosed:fp8;
- init;
- (void)dealloc;
- (char)screenSaverIsRunning;
- (char)screenSaverCanRun;
- (void)setScreenSaverCanRun:(char)fp8;
- (void)screenSaverStartNow;
- (void)screenSaverStopNow;
- (void)restartForUser:fp8;
- (double)screenSaverTimeRemaining;
- (void)screenSaverDidFade;
- (char)screenSaverIsRunningInBackground;
- (void)screenSaverDidFadeInBackground:(char)fp8 psnHi:(unsigned int)fp12 psnLow:(unsigned int)fp16;

@end

@interface ScreenSaverIPhotoAlbum:NSObject
{
    NSString *_name;
    NSString *_path;
    char _isMaster;
    NSArray *_photoDicts;
}

+ _albumDataXMLPath;
+ (char)reloadAllAlbums;
+ allAlbums;
+ albumNamed:fp8;
+ albumPathForName:fp8;
- initWithName:fp8 path:fp12 photoDicts:fp16 type:(char)fp20;
- (void)dealloc;
- description;
- (char)isMasterAlbum;
- name;
- allPhotoDicts;
- allImagePaths;
- imagesDirectory;

@end

@interface ScreenSaverApertureProject:NSObject
{
    NSString *_name;
    NSString *_path;
    char _isMaster;
    NSArray *_photoDicts;
}

+ _projectDataXMLPath;
+ (char)reloadAllProjects;
+ allProjects;
+ projectNamed:fp8;
+ projectPathForName:fp8 isMaster:(char)fp12;
- initWithName:fp8 path:fp12 photoDicts:fp16 type:(char)fp20;
- (void)dealloc;
- description;
- (char)isLibrary;
- name;
- allPhotoDicts;
- allImagePaths;
- imagesDirectory;

@end

// From secret .QuartComposer screens aver in ScreenSaver.framework

/*
 * File: .Quartz Composer
 */
@class QCPatch, QCPatchParametersView;

@interface QCPlayerView:ScreenSaverView
{
    NSOpenGLView *_glView;
    QCPatch *_patch;
    NSDictionary *_info;
    NSString *_path;
    double _startTime;
    NSDictionary *_textAttributes;
    struct _NSPoint _textPoint;
    struct _NSSize _textSize;
    struct __CVDisplayLink *_displayLink;
    NSMutableArray *_feedCache;
    NSWindow *window;
    NSButton *mainScreenButton;
    QCPatchParametersView *parametersView;
    NSTextField *parametersTextField;
    NSTableView *feedTableView;
    NSTextField *feedTextField;
}

+ (char)performGammaFade;
- (void)_saveCompositionParameters;
- (void)_restoreCompositionParameters;
- _initWithComposition:fp8 frame:(struct _NSRect)fp12 isPreview:(char)fp28;
- initWithFrame:(struct _NSRect)fp8 isPreview:(char)fp24;
- (void)dealloc;
- (void)startAnimation;
- (void)_renderFrame:fp8;
- (void)stopAnimation;
- (void)_oneStep:fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (void)animateOneFrame;
- patch;
- info;
- defaults;
- renderingOptions;
- contextOptions;

@end

@interface QCPlayerView(Configuration)
- (char)hasConfigureSheet;
- (void)done:fp8;
- configureSheet;
- (int)numberOfRowsInTableView:fp8;
- tableView:fp8 objectValueForTableColumn:fp12 row:(int)fp16;
@end
